version: '3.8'

services:
  backend:
    image: backend-app
    ports:
      - "4000:4000"
    restart: always
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

  frontend:
    image: frontend-app
    ports:
      - "5173:5173"
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-data:
    driver: local
